tosca_definitions_version: cloudify_dsl_1_3


description: >
  The blueprint first installs the VM in a separate deployment
  to connect it then with the web application installed using
  the Ansible playbook here.


imports:
  - https://cloudify.co/spec/cloudify/5.1.0/types.yaml
  - includes/hello-world-ansible.yaml


inputs:

  infrastructure_blueprint_id:
    type: string
    default: openstack-terraform-infra
    constraints:
      - valid_values:
        - openstack-infra
        - openstack-terraform-infra

  agent_user:
    description: >
      The username of the agent running on the instance created from the image.
    type: string
    default: 'ubuntu'

  agent_key_name:
    type: string
    default: agent_key

  external_network_id:
    type: string
    description: A network that provisions floating IPs.
    default: { get_secret: external_network_name }

  image_id:
    type: string
    description: The UUID of an Ubuntu Trusty 14.04 image in your Openstack account.
    default: { get_secret: ubuntu_trusty_image }

  flavor_id:
    type: string
    description: The UUID of small flavor in your Openstack account.
    default: { get_secret: small_image_flavor }

  network_id:
    type: string
    description: A name for your new Openstack Network.
    default: { get_secret: public_network_name }

  subnet_id:
    type: string
    description: A name for your new Openstack Subnet.
    default: { get_secret: public_subnet_name }


node_templates:

  vm:
    type: cloudify.nodes.ServiceComponent
    properties:
      resource_config:
        blueprint:
          id: { get_input: infrastructure_blueprint_id }
          external_resource: true
        deployment:
          auto_inc_suffix: true
          inputs:
            external_network_id: { get_input: external_network_id }
            network_id: { get_input: network_id }
            subnet_id: { get_input: subnet_id }
            image_id: { get_input: image_id }
            flavor_id: { get_input: flavor_id }
            agent_user: { get_input: agent_user }
            agent_key_name: { get_input: agent_key_name }


groups:
  vm_and_app:
    members: [vm, hello-world]


policies:
  scale_policy:
    type: cloudify.policies.scaling
    properties:
      default_instances: 1
    targets: [vm_and_app]